apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" $ }}-default-config
  labels: {{- include "redis.labels" $ | nindent 4 }}
data:
  redis.conf: |-
    include /usr/local/etc/redis/conf.d/*.conf
  01-default.conf: |-
    user default off
    user probe on nopass -@all +ping
